---
- name: check virtualization type
  assert:
    msg: "virtualization is not kvm guest"
    that:
      - "ansible_virtualization_role == 'guest'"
      - "ansible_virtualization_type == 'kvm'"


- name: check the presense of the guest agetfile
  stat:
    path: "/dev/virtio-ports/{{ ovirt_guest_agent_device }}"
  register: ovirt_guest_agent_socket

- name: "check if the device file exists"
  assert:
    that:
      - ovirt_guest_agent_socket.stat.exists
      - ovirt_guest_agent_socket.stat.islnk
    msg: "{{ ovirt_guest_agent_device }} is not symlink"